// ignore_for_file: non_constant_identifier_names

String FREE_TYPE = "for free";
String SALE_TYPE = "for sale";
String EXCHANGE_TYPE = "for exchange";
String BUY_TYPE = "for buy";

String FREE = "Free";
String EXCHANGE = "Exchange";
String SALE = "Sale";
String BUY = "Buy";


///Terms Of USe Strings
String TOU1 = "PLEASE READ THIS IMPORTANT LEGAL INFORMATION THAT GOVERNS YOUR USE OF THE IEXCHANGEIT.COM WEBSITE AND THE SERVICES.";
String TOU2 = "The iexchangeit.com connects users who wish to buy, rent or sell physical goods (for example real estate, cars and furniture) (\"Services\"). iexchangeit.com users pay for and consume these physical goods offline. In our quest to become more customer centric and increase trust and transparency for our users, the iexchangeit.com of companies also offer other services such as car inspections, car evaluations, and photography services (all provided through iexchangeit.com, a brand of iexchangeit.com). The iexchangeit.com website at www.iexchangeit.com and the mobile application of the online platform (collectively the \"Website\" or \"Platforms\") are used to connect buyers and sellers and are owned by iexchangeit.com mainland services such as car inspections, evaluations and car brokering services are carried out by iexchangeit.com.";
String TOU3 = "These Terms of Service provide you with information about the terms upon which we agree to provide, permit and allow you to access and use "
    "the Website. Please print a copy of these Terms of Service and refer to it as you use our Systems and Services. You agree to be bound by these Terms "
    "of Service if you continue using the Website. If you do not agree to these Terms of Service, you must immediately refrain from using the Website and "
    "the Services.";
String TOU4 = "We may make changes to the Terms of Service and will notify you of these changes by changing the date “last modified” above. IF ANY FUTURE "
    "CHANGES ARE UNACCEPTABLE TO YOU, YOU SHOULD DISCONTINUE USING THE SYSTEMS AND SERVICES. YOU’RE CONTINUED USE OF THE SYSTEMS AND SERVICES NOW OR "
    "FOLLOWING THE POSTING OF ANY SUCH CHANGES WILL INDICATE YOUR ACCEPTANCE OF THESE TERMS AND ANY CHANGES.\nIf you are a company advertising in our "
    "Property, Motors or Jobs categories, you will be required to enter additional terms and conditions set out in our Advertising Order Form, however, "
    "please note that these Terms of Service will still apply and must be read in conjunction with any other agreement you enter with iexchangeit.com.";


String acceptance = "1. Acceptance of these Term of Service";
String TOU5 = "1.1 The Website and the Service are provided to you subject to these Terms of Service (these \"Terms\"). By accessing the Website or using "
    "the Service, you agree that you have read, understood and agree to be bound by these Terms. For the purpose of the Terms and wherever the context so "
    "requires, the terms 'you' and “your” shall mean any person who uses the Website or the Service in any manner whatsoever including persons browsing "
    "the Website and its content, posting comments or any content or responding to any advertisements or content on the Website.\n1.2 By accessing and/or "
    "using the Website and/or the Service, you agree to comply with these Terms. Additionally, when using a portion of the Service, you agree to conform to"
    " any applicable posted guidelines for such Service, which may change or be updated from time to time at iexchangeit.com sole discretion.\n1.3 You are "
    "solely responsible for reviewing these Terms from time to time. Should you object to any term or condition of these Terms, any guideline, or any "
    "subsequent changes thereto or become unhappy with iexchangeit.com or the Service in any way, you must immediately discontinue use of the Website "
    "and the Service.\n1.4 These Terms may be updated by iexchangeit.com at any time at its sole discretion. It is your responsibility to keep a copy of "
    "these Terms and check the date “last modified” at the top of this page.\n1.5 iexchangeit.com may provide a translation of the English version of the "
    "Terms into other languages. Any translation of the Terms into other languages is for your convenience only and the English version governs the "
    "terms of your relationship with iexchangeit.com. Furthermore, if there are any inconsistencies between the English version of the Terms and any "
    "translation, the English version of the Terms shall prevail.\n1.6 The term \"affiliates\" as referred to in Sections 10 and 20 of these Terms means: "
    "any company controlled or owned by iexchangeit.com; any company commonly controlled or owned with iexchangeit.com; or any group entity jointly "
    "offering the Service.";


String description = "2. Description of Service and Content Policy";
String TOU6 = "2.1 This Section 2 has important legal consequences for you. In this section: - the legal responsibilities and liabilities of "
    "iexchangeit.com are excluded or limited; - you take on risk, responsibilities and liability; and - any rights you have against iexchangeit.com "
    "are limited or excluded. The statements made in this section constitute acknowledgements of fact by you. You must read these statements carefully "
    "and ensure they are correct, as you will not be able to deny the truth of the statements. iexchangeit.com and/or other persons may have claims and "
    "other rights against you as a result of these statements.\n2.2 iexchangeit.com is a platform to allow our users who comply with these Terms to offer, "
    "sell, and buy products and services listed on the Website. Although you may be able to conduct payment and other transactions through the Website, "
    "using third-party vendors, iexchangeit.com is not in any way involved in such transactions. As a result, and as discussed in more detail in these "
    "Terms, you hereby acknowledge and agree that iexchangeit.com is not a party to such transactions, has no control over any element of such "
    "transactions, and, as far as the law allows, shall have no liability towards any party in connection with such transactions. As far as the law "
    "allows, you use the Service and the Website at your sole risk and responsibility.\n2.3 You understand that iexchangeit.com is not responsible for "
    "ads, directory information, business listings/information, messages between users, including without limitation e-mails or chats or other means of "
    "electronic communication, whether through the Website or another Third Party Website (defined below) or offerings, comments, user postings, files, "
    "images, photos, video, sounds, business listings/information and directory information or any other material made available through the Website and "
    "the Service (\"Content\"), and that by using the Website and the Service, you may be exposed to Content that is offensive, indecent, inaccurate, "
    "misleading, or otherwise objectionable. As far as the law allows, you are responsible for and must evaluate, and bear all risks associated with, "
    "the use of any Content. You may not rely on said Content, and under no circumstances will iexchangeit.com be liable in any way for the Content or "
    "for any loss or damage of any kind incurred as a result of the browsing, using or reading any Content listed, e-mailed or otherwise made available "
    "via the Service. iexchangeit.com is not obliged to pre-screen or approve any Content, but iexchangeit.com has the right, in its sole and absolute "
    "discretion, to refuse, delete or move any Content that is or may be available through the Service, for violating these Terms and such violation "
    "being brought to iexchangeit.com knowledge or for any other reason or no reason at all. Furthermore, the Website and Content available through the "
    "Website may contain links to other third party websites (\"Third Party Websites\"), which are completely unrelated to iexchangeit.com. If you link to "
    "Third Party Websites, you may be subject to those Third Party Websites’ terms and conditions and other policies. As far as the law allows, "
    "iexchangeit.com makes no representation or guarantee as to the accuracy or authenticity of the information contained in any such Third Party "
    "Websites, and your linking to any other websites is, as far as the law allows, completely at your own risk and iexchangeit.com disclaims all "
    "liability thereto.\n2.4 You are solely responsible for your own Content posted on, transmitted through, or linked from the Service and the "
    "consequences of posting, transmitting, linking or publishing it. More specifically, you are solely responsible for all Content that you upload, "
    "email or otherwise make available via the Service. In connection with such Content posted on, transmitted through, or linked from the Service by you,"
    " you affirm, acknowledge, represent, warrant and covenant that:\n\t(i) you own or have and shall continue to, for such time the Content is available "
    "on the Website, have the necessary licenses, rights, consents, and permissions to use such Content on the Service and Website (including without "
    "limitation all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all such Content) and authorize "
    "iexchangeit.com to use such Content to enable inclusion and use of the Content in the manner contemplated by the Service, the Website and these "
    "Terms; and\n\t(ii) you have the written consent, release, and/or permission of each and every identifiable individual person or business in the "
    "Content to use the name or likeness of each and every such identifiable individual person or business to enable inclusion and use of the "
    "Content in the manner contemplated by the Service, the Website and these Terms. For clarity, you retain all of your ownership rights in "
    "your Content; however, by submitting any Content on the Website, you hereby grant to iexchangeit.com an irrevocable, non-cancellable, perpetual,"
    " worldwide, non-exclusive, royalty-free, sub-licensable, transferable license to use, reproduce, distribute, prepare derivative works of, display, "
    "and perform the Content in connection with the Website and iexchangeit.com (and its successors') business, including without limitation for the "
    "purpose of promoting and redistributing part or all of the Website and Content therein (and derivative works thereof) in any media formats and "
    "through any media channels now or hereafter known. These rights are required by iexchangeit.com in order to host and display your Content. "
    "Furthermore, by you posting Content to any public area of the Service, you agree to and do hereby grant to iexchangeit.com all rights necessary "
    "to prohibit or allow any subsequent aggregation, display, copying, duplication, reproduction, or exploitation of the Content on the Service or "
    "Website by any party for any purpose which contravenes these Terms. These rights are perpetual and cannot be revoked by you and will apply and "
    "can be exercised throughout the world. You also hereby grant each user of the Website a non-exclusive license to access your Content through the "
    "Website (this license excludes automated data collection/scraping cases and any other possible use with commercial purposes). The foregoing license "
    "to each user granted by you terminates once you or iexchangeit.com remove or delete such Content from the Website.\n2.5 iexchangeit.com does not "
    "endorse any Content or any opinion, statement, recommendation, or advice expressed therein, and, as far as the law allows, iexchangeit.com "
    "expressly disclaims any and all liability in connection with user Content. iexchangeit.com does not permit copyright infringing activities "
    "and infringement of intellectual property rights on the Website, and iexchangeit.com may, at its sole discretion, remove any infringing Content. "
    "iexchangeit.com reserves the right to remove any Content without prior notice. iexchangeit.com may also terminate a user's access to the Website. "
    "Further, at its sole discretion, iexchangeit.com reserves the right to decide whether any Content is appropriate and complies with these Terms.";

String featuredAds = "3. Featured Ads";
String TOU7 = "3.1 iexchangeit.com offers a service known as \"Featured Ads\" where users may pay a non-refundable fee to have their ads "
    "posted in selected locations on the Website, thus potentially increasing an ads' visibility. In order to purchase a Featured Ad, you "
    "may be required to transmit certain information through a third party service provider, Click & Buy, a Third Party Website, that may be "
    "governed by its own terms of use and other policies. iexchangeit.com makes no representation or guarantee as to the safety or security of "
    "the information transmitted to any Third Party Website, and your linking to any Third Party Website is completely at your own risk, and "
    "iexchangeit.com disclaims all liability related thereto.";


String conduct = "4. Conduct";
String TOU8 = "You agree not to post, email, host, display, upload, modify, publish, transmit, update or share any information on the Site, or otherwise "
    "make available Content:\n4.1 that violates any law or regulation; \n4.2 that is copyrighted or patented, protected by trade secret or trademark, "
    "or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have "
    "permission or a license from their rightful owner to post the material and to grant iexchangeit.com all of the license rights granted herein;"
    "\n4.3 that infringes any of the foregoing intellectual property rights of any party, or is Content that you do not have a right to make available "
    "under any law, regulation, contractual or fiduciary relationship(s);"
    "\n4.4 that is harmful, abusive, unlawful, threatening, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, "
    "invasive of another's privacy or other rights, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money "
    "laundering or illegal gambling or harms or could harm minors in any way or otherwise unlawful in any manner whatsoever;"
    "\n4.5 that harasses, degrades, intimidates or is hateful towards any individual or group of individuals on the basis of religion, "
    "gender, sexual orientation, race, ethnicity, age, or disability;"
    "\n4.6 that violates any (local) equal employment laws, including but not limited to those prohibiting the stating, in any advertisement for "
    "employment, a preference or requirement based on race, color, religion, sex, national origin, age, or disability of the applicant;"
    "\n4.7 that includes personal or identifying information about another person without that person's explicit consent;"
    "\n4.8 that impersonates any person or entity, including, but not limited to, a iexchangeit.com employee, or falsely states or otherwise misrepresents"
    " an affiliation with a person or entity;"
    "\n4.9 deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing "
    "in nature;"
    "\n4.10 that is false, deceptive, misleading, deceitful, misinformative, or constitutes \"bait and switch\" offer;"
    "\n4.11 that constitutes or contains \"pyramid schemes\", \“jokes\”, \"affiliate marketing\", \"link referral code,\" \"junk mail,\" \"spam,\" \"chain letters,\" "
    "\"bait marketing\", \"negative option marketing\", \"referral selling\" or unsolicited advertisements of a commercial nature;"
    "\n4.12 that constitutes or contains any form of advertising or solicitation if (i) posted in areas or categories of the Website which are "
    "not designated for such purposes; or (ii) e-mailed to iexchangeit.com users who have requested not to be contacted about other services, "
    "products or commercial interests;"
    "\n4.13 that includes links to commercial services or Third Party Websites, except as specifically allowed by iexchangeit.com"
    "\n4.14 that advertises any illegal services or the sale of any items the sale of which is prohibited or restricted by applicable law, "
    "including without limitation items the sale of which is prohibited or regulated by applicable law;"
    "\n4.15 that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of "
    "any computer software or hardware or telecommunications equipment or any other computer resource;"
    "\n4.16 that disrupts the normal flow of dialogue with an excessive number of messages (flooding attack) to the Service, or that otherwise "
    "negatively affects other users' ability to use the Service; or"
    "\n4.17 that employs misleading email addresses, or forged headers or otherwise manipulated identifiers in order to disguise the origin "
    "of Content transmitted through the Service."
    "\n\nAdditionally, you agree not to:"
    "\n4.18 contact anyone who has asked not to be contacted, or make unsolicited contact with anyone for any commercial purpose, "
    "specifically, contact any user to post advertisement on a third party Website or post any advertisement on behalf of such user; or to "
    "\"stalk\" or otherwise harass anyone;"
    "\n4.19 make any libelous or defamatory comments or postings to or against anyone;"
    "\n4.20 collect personal data about other users or entities for commercial or unlawful purposes;"
    "\n4.21 use automated means, including spiders, robots, crawlers, data mining tools, or the like to download or scrape data from the "
    "Service, except for internet search engines (e.g,. Google) and non-commercial public archives (e.g. archive.org) that comply with our "
    "robots.txt file;"
    "\n4.22 post Content that is outside the local area or not relevant to the local area, repeatedly post the same or similar Content, or "
    "otherwise impose unreasonable or disproportionately large loads on our servers and other infrastructure;"
    "\n4.23 post the same item or service in multiple classified categories or forums, or in multiple metropolitan areas;"
    "\n4.24 attempt to gain unauthorized access to computer systems owned or controlled by iexchangeit.com or engage in any "
    "activity that disrupts, diminishes the quality of, interferes with the performance of, or impairs the functionality of, "
    "the Service or the Website;"
    "\n4.25 use any form of automated device or computer program (sometimes referred to as \"flagging tools\") "
    "that enables the use of iexchangeit.com \"flagging system\" or other community control systems without each flag being manually "
    "entered by a human that initiates the flag (an \"automated flagging device\"), or use any such flagging tool to remove posts of competitors, "
    "other third parties or to remove posts without a reasonable good faith belief that the post being flagged violates these Terms or any applicable law "
    "or regulation; or"
    "\n4.26 use any automated device or software that enables the submission of automatic postings on iexchangeit.com without human "
    "intervention or authorship (an \"automated posting device\"), including without limitation, the use of any such automated posting device "
    "in connection with bulk postings, or for automatic submission of postings at certain times or intervals."
    "\n4.27 Any Content uploaded by you shall be subject to relevant laws and may disabled, or and may be subject to "
    "investigation under appropriate laws. Furthermore, if you are found to be in non-compliance with the laws and regulations, these terms, or the "
    "privacy policy of the Site, we may terminate your account/block your access to the Site and we reserve the right to remove any non-compliant Content "
    "uploaded by you.";

String paidPosting = "5. Paid Postings";
String TOU9 = "5.1 iexchangeit.com may charge a fee to post Content in some specific areas of the Service (Paid Content). "
    "The fee permits Paid Content to be posted in a designated area of the Website. Each party posting Paid Content to the Service is responsible for "
    "the Content and compliance with the Terms. Any such fees paid hereunder are non-refundable in the event any Content is removed from the Service "
    "for violating these Terms. Additional terms regarding Paid Content will be fully stated in the applicable section(s)."
    "\n5.2 All Job ads that announce several positions in one ad will be deleted after 24h of their posting and no refund will be given. "
    "Within the first 24h of the posting, the user can edit the multiple-position ad to reduce it to one position. If the ad does not get edited "
    "to fulfill iexchangeit.com requirements, the ad will be deleted and no refund given.";

String postingAgents = "6. Posting Agents";
String TOU10 = "6.1 As used herein, the term \"Posting Agent\" refers to a third-party agent, service or intermediary that offers to post Content to "
    "the Service on behalf of others. iexchangeit.com prohibits the use of Posting Agents, directly or indirectly, without the express written "
    "permission of iexchangeit.com. In addition, Posting Agents are not permitted to post Content on behalf of others, directly or indirectly, or "
    "otherwise access the Service in order to post Content on behalf of others, except with express written permission or license from iexchangeit.com.";

String accessService = "7. Access to the Service";
String TOU11 = "7.1 iexchangeit.com grants you a limited, revocable, non-exclusive license to access and use the Service for personal use. "
    "This license granted herein does not include any of the following: (a) access to or use of the Service by Posting Agents; or (b) any collection, "
    "aggregation, copying, duplication, display or derivative use of the Service nor any use of data mining, robots, spiders, or similar data gathering "
    "and extraction tools for any purpose unless expressly permitted by iexchangeit.com or as otherwise set forth in these Terms. Notwithstanding the "
    "foregoing, general purpose internet search engines and non-commercial public archives that gather information for the sole purpose of displaying"
    " hyperlinks to the Service, provided they each do so from a stable IP address or range of IP addresses using an easily identifiable agent and "
    "comply with our robots.txt file, may engage in the activities set forth in (b). For purposes of this exception, a \"general purpose internet "
    "search engine\" does not include a website or search engine or other service that specializes in classified listings including any subset of "
    "classifieds listings such as housing, for sale, jobs, services, or personals, or which otherwise provides classified ad listing services. "
    "The license set forth in this Section permits you to display on your website, or create a hyperlink thereto, individual postings on the Service "
    "so long as such use is for non-commercial and/or news reporting purposes only (e.g., for use in personal blogs or other personal online media). "
    "iexchangeit.com may limit the amount of postings displayed on or linked to your website. Use of the Service beyond the scope of authorized access "
    "as set forth in these Terms immediately terminates any permission or license granted herein. In order to collect, aggregate, copy, duplicate, "
    "display or make derivative use of the Service or any Content made available via the Service for other purposes (including commercial purposes) "
    "not stated herein, you must first obtain a license from iexchangeit.com.";


String notificationClaims = "8. Notification of Claims of Infringements";
String TOU12 = "8.1 If you are an owner of intellectual property rights or an agent who is fully authorised to act on behalf of the owner of "
    "intellectual property rights and believe that any Content or other content infringes upon your intellectual property right or intellectual "
    "property right of the owner on whose behalf you are authorised to act, you may submit a notification to iexchangeit.com together with a request "
    "to iexchangeit.com to delete the relevant Content in good faith. The notification and the request must contain the following information:"
    "\n\t8.1.1 A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;"
    "\n\t8.1.2 Identification of the intellectual property rights claimed to have been infringed, or, if multiple intellectual property rights at a "
    "single online site are covered by a single notification, a representative list of such works at that site;"
    "\n\t8.1.3 Identification of the Content (by means of data or communication link, etc.) that is claimed to be infringing or to be the subject of "
    "infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit iexchangeit.com "
    "to locate the material;"
    "\n\t8.1.4 Information reasonably sufficient to permit iexchangeit.com to contact you, such as an address, telephone number, and an electronic mail "
    "address;"
    "\n\t8.1.5 A signed statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the "
    "intellectual property right-owner, its agent, or the law;"
    "\n\t8.1.6 A signed statement that the intellectual property-owner hold iexchangeit.com harmless from any claim of any third party in connection "
    "with the removing by iexchangeit.com of the relevant content; and"
    "\n\t8.1.7 A signed statement that the information in the notification is accurate and under penalty of perjury that you are authorized to act on "
    "behalf of the owner of an exclusive right that is allegedly infringed."
    "Notifications must be sent to: admin@iexchangeit.com.";

String intellectualProp = "9. Intellectual Property Rights";
String TOU13 = "9.1 The materials on the Website, other than the user Content that you licensed under these Terms, including without limitation, "
    "the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like (\"Materials\") and the trademarks, "
    "service marks and logos contained therein (\"Marks\"), are owned by or licensed to iexchangeit.com, and are subject to copyright and other "
    "intellectual property rights under United Arab Emirates and foreign laws and international conventions. In connection with the Services, the "
    "Website may display certain intellectual property goods belonging to third parties. Use of these goods may be subject to license granted by "
    "third parties to iexchangeit.com. You shall, in no event, reverse engineer, decompile, or disassemble such goods and nothing herein shall be "
    "construed to grant you any right in relation to such goods. Materials on the Website are provided to you AS IS for your information and personal "
    "use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for "
    "any other purposes whatsoever without the prior written consent of the respective owners. iexchangeit.com reserves all rights not expressly "
    "granted herein to the Website and the Materials. You agree to not engage in the use, copying, or distribution of any of the Materials other "
    "than as expressly permitted herein, including any use, copying, or distribution of Materials of third parties obtained through the Website for "
    "any commercial purposes. . You agree not to circumvent, disable or otherwise interfere with security related features of the Website or features "
    "that prevent or restrict use or copying of any Materials or enforce limitations on use of the Website or the Materials therein. Content "
    "displayed on or through the Service is protected by copyright as a collective work and/or compilation, pursuant to copyrights laws, other laws, "
    "and international conventions. Any reproduction, modification, creation of derivative works from or redistribution of the Website, the Materials, "
    "or the collective work or compilation is expressly prohibited. Copying or reproducing the Website, the Materials, or any portion thereof for "
    "further reproduction or redistribution is expressly prohibited.";

String userSubmissions = "10. User Submissions";
String TOU14 = "10.1 This Section 10 has important legal consequences for you. In this section: - the legal responsibilities and liability of "
    "iexchangeit.com are limited or excluded; - the rights or remedies you may have against iexchangeit.com are limited or excluded; and - you take "
    "on risk, responsibilities and liability. You accept that various things can go wrong when using the Website and/or the Service, and/or when "
    "viewing and/or using the Content. You take on the responsibility and liability of these events happening and will have no claim against "
    "iexchangeit.com if they happen. When using the Website, you will be exposed to Content from a variety of sources, and that, as far as the law "
    "allows, iexchangeit.com is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Content, "
    "and you agree and assume all liability for your use. You further may be exposed to Content that is inaccurate, offensive, indecent, objectionable, "
    "defamatory or libelous and, as far as the law allows, and subject to Section 19, you agree to waive, and hereby do waive, any legal or equitable "
    "rights or remedies you have or may have against iexchangeit.com with respect thereto.";

String indeminity = "11. Indemnity";
String TOU15 = "11.1 This Section 11 has important legal consequences for you. In this section: - the legal responsibilities and liability of "
    "iexchangeit.com are limited or excluded; - the rights or remedies you may have against iexchangeit.com are limited or excluded; and - you "
    "take on risk, responsibilities and liability. - you indemnify iexchangeit.com and other persons against liability and claims.As far as the "
    "law allows, and subject to Section 19, you agree to defend, indemnify and hold harmless iexchangeit.com, its officers, subsidiaries, affiliates, "
    "successors, assigns, directors, officers, agents, service providers, suppliers and employees, from and against any and all claims, damages, "
    "obligations, losses (whether direct, indirect or consequential),, liabilities, costs or debt, and expenses (including but not limited to attorneys' "
    "fees) arising from: (i) your violation of any provision of these Terms; (ii) your violation of any third party right, including without "
    "limitation any copyright, trademark, trade secret or other property, or privacy right; or (iii) any claim that your Content caused damage to a "
    "third party. As far as the law allows, and subject to Section 19, this defence and indemnification obligation will survive termination, "
    "modification or expiration of these Terms and your use of the Service and the Website.";

String noSpam = "12. No Spam Policy";
String TOU16 = "12.1 This Section 12 has important legal consequences for you. In this section you take on risk, responsibilities and liability. "
    "This may result in you being punished under applicable criminal laws, and/or you becoming financially liable to iexchangeit.com and/or other "
    "persons for additional amounts. You understand and agree that sending unsolicited email advertisements or other unsolicited communications "
    "to iexchangeit.com email addresses or through iexchangeit.com computer systems are expressly prohibited by these Terms. You acknowledge and "
    "agree that from time to time iexchangeit.com may monitor email usage using human monitors or automated software to flag certain words associated "
    "with spam or scams in emails that are sent between one users to another in the iexchangeit.come-mail system. Any communication between yourself "
    "and any other user utilizing the communication features available on the Service and the Website may be used only in accordance with the Terms. "
    "Any unauthorized use of iexchangeit.com computer systems is a violation of these Terms and certain applicable laws, in particular the Pakistan "
    "Cybercrimes legislation. Such violations may subject the sender and his or her agents to civil and criminal penalties. Please note that the "
    "Pakistan Cybercrimes legislation carries significant penalties including imprisonment. In case you intend to solicit, or contact our users by "
    "obtaining their email or phone numbers from our Website, we may report this behavior to the relevant authorities, who then may decide to prosecute"
    " you under the relevant Pakistan laws.";

String orgIndvDeals = "13. Dealings with Organizations and Individuals";
String TOU17 = "13.1 This Section 13 has important legal consequences for you. In this section: - the legal responsibilities and liability of "
    "iexchangeit.com are limited or excluded; - the rights or remedies you may have against iexchangeit.com are limited or excluded; and - you"
    " take on risk, responsibilities and liability. As far as the law allows, and subject to Section 19, iexchangeit.com shall not be liable for "
    "your interactions with any organizations and/or individuals on the Website or through the Service. This includes, but is not limited to, payment "
    "and delivery of goods and services, and any other terms, conditions, warranties or representations associated with any interaction you may have "
    "with other organizations and/or individuals. These dealings are solely between you and such organizations and/or individuals. As far as the law "
    "allows, and subject to Section 19, iexchangeit.com shall not be responsible or liable for any loss or damage of any sort incurred as the result "
    "of any such dealings or interactions. In the event that you have a dispute with one or more other users, as far as the law allows, and subject to "
    "Section 19, you hereby release iexchangeit.com, its officers, employees, agents and successors from any and all claims, demands and damages "
    "(actual and consequential) of every kind or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or "
    "in any way related to such disputes and/or our Service.";

String Limitations = "14. Limitation and Termination of Service";
String TOU18 = "14.1 This Section 14 has important legal consequences for you. In this section: - the legal responsibilities and liability of "
    "iexchangeit.com are limited or excluded; - the rights or remedies you may have against iexchangeit.com are limited or excluded; and - you "
    "take on risk, responsibilities and liability. iexchangeit.com may establish limits from time to time concerning use of the Service, including "
    "among others, the maximum number of days that Content will be maintained or retained by the Service, the maximum number and size of postings, "
    "e-mail messages, or other Content that may be transmitted or stored by the Service, and the frequency with which you may access the Service or "
    "the Website. As far as the law allows and subject to Section 19, iexchangeit.com has no responsibility or liability for the deletion or failure "
    "to store any Content maintained or transmitted by the Website or the Service. iexchangeit.com reserves the right at any time to modify or "
    "discontinue the Service (or any part thereof) with or without notice, and that iexchangeit.com shall not be liable to you or to any third "
    "party for any such modification, suspension or discontinuance of the Service. You acknowledge and agree that iexchangeit.com, in its sole "
    "and absolute discretion, has the right (but not the obligation) to delete or deactivate your account, block your e-mail or IP address, or "
    "otherwise terminate your access to or use of the Service (or any part thereof), immediately and without notice, and remove and discard any "
    "Content within the Service, for any reason or no reason at all. Further, as far as the law allows, and subject to Section 19, you agree that "
    "iexchangeit.com shall not be liable to you or any third-party for any termination of your access to the Website or the Services.";

String assignment = "15. Assignment";
String TOU19 = "15.1 These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by "
    "iexchangeit.com without restriction. Any assignment or transfer by you shall be null and void.";

String acceptTerms = "16. Ability to Accept Terms of Service";
String TOU20 = "16.1 This Website is intended only for adults and you warrant that you are eligible to contract as per applicable laws. "
    "If you are using/accessing this Website as a representative of any person/entity, you acknowledge that you are legally authorized "
    "to represent that person/entity. Minors are only allowed to access the Website and use the Service, in the event of approval of their "
    "legal representatives or in the event that it concerns an act or a transaction that is usual and acceptable standard in civil life and "
    "practice. You affirm that you are either at least 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, "
    "and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth "
    "in these Terms, and to abide by and comply with these Terms.";

String generalInfo = "17. General Information";
String TOU21 = "17.1 These Terms and the other policies posted on the Website constitute the complete and exclusive understanding and agreement "
    "between you and iexchangeit.com and govern your use of the Service and the Website superseding all prior understandings, proposals, agreements,"
    " negotiations, and discussions between the parties, whether written or oral. The Terms and the relationship between you and iexchangeit.com "
    "shall be governed by the laws of the United Arab Emirates without regard to its conflict of law principles. We encourage you to contact "
    "iexchangeit.com to try and settle any claim you may have, however, if we cannot settle the dispute amicably through human negotiation, "
    "then the claim or dispute must be submitted to the exclusive jurisdiction of the courts located within the United Arab Emirates. The failure "
    "of iexchangeit.com to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision. If any "
    "provision of the Terms is found by a court of competent jurisdiction to be invalid (including, without limitation, because such provision is "
    "inconsistent with the laws of another jurisdiction) or inapplicable, the parties nevertheless agree that the court should endeavour to give effect "
    "to the parties' intentions as reflected in the provision. If any provision or provisions of these Terms is held to be invalid, illegal or "
    "unenforceable, the validity, legality and enforceability of the remaining provisions of the Terms shall not in any way be affected or be impaired. "
    "YOU AGREE THAT ANY CAUSE OF ACTION BROUGHT BY YOU AND ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE AND/OR THE WEBSITE MUST COMMENCE "
    "WITHIN A REASONABLE TIME AND IN ANY EVENT WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. These Terms shall inure to the benefit of and "
    "be binding upon each party's successors.";

String termsVoilation = "18. Violation of Terms and Liquidated Damages";
String TOU22 = "18.1 This Section 18 has important legal consequences for you. In this section: - the legal responsibilities and liability of "
    "iexchangeit.com are limited or excluded; - the rights or remedies you may have against iexchangeit.com are limited or excluded; and - you "
    "take on risk, responsibilities and liability. This may result in you becoming financially liable to iexchangeit.com for additional amounts. "
    "The statements made in this section also constitute acknowledgements of fact by you. You must read these statements carefully and ensure they "
    "are correct, as you will not be able to deny the truth of the statements. iexchangeit.com and/or other persons may have claims and other rights "
    "against you as a result of these statements. Please report any violations of the Terms that you become aware of by contacting us using the link "
    "at the bottom of the Website's homepage at www.iexchangeit.com. Any failure to act by iexchangeit.com with respect to a breach by you or others "
    "does not waive our right to act with respect to subsequent or similar breaches by you or others.";

String warranties = "19. Disclaimer of Warranties";
String TOU23 = "19.1 This Section 19 has important legal consequences for you. In this section: - the legal responsibilities and "
    "liability of iexchangeit.com are limited or excluded; - the rights or remedies you may have against iexchangeit.com are limited "
    "or excluded; and - you take on risk, responsibilities and liability. There are things that may go wrong when using the Website and/or "
    "the Service, including what is listed in this Section 19. iexchangeit.com is not responsible (liable) for anything that goes wrong, "
    "including what is listed in this Section."
    "\n19.2 You use the Website and the Service knowing and accepting that these things can go wrong "
    "and that there are risks. "
    "\nAS FAR AS THE LAW ALLOWS, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE WEBSITE AND THE"
    " SERVICE IS ENTIRELY AT YOUR OWN RISK AND THAT THE WEBSITE AND THE SERVICE ARE PROVIDED ON AN \"AS IS\" OR \"AS AVAILABLE\" "
    "BASIS, WITHOUT ANY WARRANTIES OF ANY KIND. ALL EXPRESS AND IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, "
    "THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS ARE EXPRESSLY "
    "DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. TO THE FULLEST EXTENT PERMITTED BY LAW, iexchangeit.com, ITS OFFICERS, DIRECTORS, "
    "EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND YOUR USE THEREOF. iexchangeit.com "
    "MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE WEBSITE'S CONTENT OR THE CONTENT OF ANY THIRD PARTY"
    " WEBSITES LINKED TO THE WEBSITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY \n(I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, "
    "\n(II)PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE WEBSITE AND SERVICE, \n(III) "
    "ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, \n(IV) "
    "ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITE, \n(V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE "
    "TRANSMITTED TO OR THROUGH THE WEBSITE BY ANY THIRD PARTY, AND/OR \n(VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF "
    "ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, COMMUNICATED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE "
    "WEBSITE OR THE SERVICE. iexchangeit.com DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE "
    "ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE WEBSITE OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, "
    "AND iexchangeit.com WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND/OR OTHER "
    "USERS AND/OR THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR "
    "IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE. AS FAR AS THE LAW ALLOWS, "
    "AND SUBJECT TO SECTION 19, IN NO EVENT SHALL iexchangeit.com, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE FOR "
    "DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF iexchangeit.com HAS BEEN ADVISED OF THE "
    "POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY ASPECT OF YOUR USE OF THE WEBSITE OR THE SERVICE, INCLUDING WITHOUT LIMITATION"
    " WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF THE WEBSITE OR THE SERVICE, FROM INABILITY TO USE THE WEBSITE OR THE SERVICE,"
    " OR THE INTERRUPTION, SUSPENSION, MODIFICATION, ALTERATION, OR TERMINATION OF THE WEBSITE OR THE SERVICE, (iv) ERRORS, MISTAKES, "
    "OR INACCURACIES OF CONTENT, (v) PERSONAL INJURY OR PROPERTY DAMAGE RESULTING FROM YOUR ACCESS TO AND USE OF THE WEBSITE AND SERVICE, "
    "\n(VII) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, "
    "\n(VIII) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITE, "
    "\n(IX) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE WEBSITE BY ANY THIRD PARTY, "
    "\n(X) ANY ERRORS OR OMISSIONS IN ANY CONTENT, (x) ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, "
    "EMAILED, COMMUNICATED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE WEBSITE OR THE SERVICE. SUCH LIMITATION OF LIABILITY SHALL "
    "ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH "
    "THE WEBSITE OR THE SERVICE OR ANY LINKS ON THE WEBSITE, AS WELL AS BY REASON OF ANY INFORMATION, OPINIONS OR ADVICE RECEIVED THROUGH OR "
    "ADVERTISED IN CONNECTION WITH THE WEBSITE OR THE SERVICE OR ANY LINKS ON THE iexchangeit.com SITE. THESE LIMITATIONS SHALL APPLY TO THE "
    "FULLEST EXTENT PERMITTED BY LAW. AS FAR AS THE LAW ALLOWS, AND SUBJECT TO SECTION 19, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT "
    "iexchangeit.com SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY USER OR "
    "THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. iexchangeit.com MAKES NO REPRESENTATIONS "
    "OR WARRANTIES THAT THE WEBSITE IS APPROPRIATE FOR USE IN OTHER LOCATIONS. THOSE WHO ACCESS OR USE THE WEBSITE FROM OTHER JURISDICTIONS DO "
    "SO AT THEIR OWN VOLITION AND RISK AND ARE RESPONSIBLE FOR COMPLIANCE WITH LOCAL LAW.";

String abilityLimitations = "20. Limitations of Liability";
String TOU24 = "20.1 IN NO EVENT SHALL iexchangeit.com, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE FOR DIRECT, INDIRECT, INCIDENTAL, "
    "SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF iexchangeit.com HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM "
    "ANY ASPECT OF YOUR USE OF THE WEBSITE OR THE SERVICE, INCLUDING WITHOUT LIMITATION WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF THE WEBSITE "
    "OR THE SERVICE, FROM INABILITY TO USE THE WEBSITE OR THE SERVICE, OR THE INTERRUPTION, SUSPENSION, MODIFICATION, ALTERATION, OR TERMINATION OF "
    "THE WEBSITE OR THE SERVICE. SUCH LIMITATION OF LIABILITY SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR PRODUCTS "
    "RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE WEBSITE OR THE SERVICE OR ANY LINKS ON THE WEBSITE, AS WELL AS BY REASON OF ANY INFORMATION, "
    "OPINIONS OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE WEBSITE OR THE SERVICE OR ANY LINKS ON THE iexchangeit.com SITE. THESE "
    "LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT iexchangeit.com SHALL NOT BE LIABLE "
    "FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY USER OR THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE "
    "FOREGOING RESTS ENTIRELY WITH YOU.\nThe Website is controlled and offered by iexchangeit.com from its facilities in "
    "PAKISTAN. iexchangeit.com makes no representations or warranties that the Website is appropriate for use in other locations. "
    "Those who access or use the Website from other jurisdictions do so at their own volition and risk and are responsible for compliance with local "
    "law.";

String propertySale = "21. Property For Sale and Property for Rent Categories on iexchangeit.com";
String TOU25 = "If you are listing a property on this Website, your obligations are as follows:\n\nAll Advertisers"
    "\ni. You may only advertise properties that are currently available for sale or lease. It is at our discretion to remove any listings (advertising "
    "fees will not be refunded);"
    "\nii. You warrant that the advertisement does not contain unlawful language or use of the premises, including:"
    "\n\ta. defamatory, misleading or deceptive statements;"
    "\n\tb. sharing of a property that exceeds lawful occupancy limits (including, but not limited to, bachelor accommodations and multi-family use);"
    "\n\tc. sharing of a property between unrelated members of the opposite sex;"
    "\n\td. sharing of a property in any way that is deemed unlawful;"
    "\n\te. any other language that promotes illegal or immoral activities under the laws of the Land."
    "\n\nIf you are listing a property on this Website, your obligations are as follows:"
    "\n\ti. iexchangeit.com advertisements include real properties for sale or rent. iexchangeit.com is not a real estate brokerage and the details of "
    "the properties available on this Website are provided to us by third party brokers, landlords, owners or developers."
    "\n\tii. iexchangeit.com does not verify the property listing details provided to us by third parties, and makes no warranties or representations "
    "as to their accuracy or completeness."
    "\n\tiii. You the User of this Website must conduct your own due diligence and must not rely on the details in the advertisements."
    "\n\tiv. iexchangeit.com does verify license number of all property broker companies prior to allowing them to advertise on the Website.";

String motors = "22. Motors Category";
String TOU26 = "As a user of the Website, you must not offer for sale any type of car, motor vehicle or motorcycle (“Vehicle”) that is:"
    "\n\t(i) located outside of the Pakistan, unless you can prove ownership of the Vehicle upon request"
    "\n\t(ii) that is not immediately for sale;"
    "\n\t(iii) that is not accurately described by the category in which it is advertised;"
    "\n\t(iv) that you are not the owner of, or in all other cases, which you do not have the rights to sell;"
    "\n\t(v) without true and accurate pricing of the Vehicle displayed within the listing."
    "\n\nWe may request that you provide proof of ownership and that the Vehicle is located in the pakistan or has been cleared by customs. "
    "If you do not provide us with proof within 24 hours of request, we may immediately remove the relevant advertisement/content without further"
    " notice and no refund will be made.";

String automatedData = "23. Automated data collection";
String TOU27 = "23.1 As a user of the Website, you expressly agree not to use any form of automated data collection such as harvesting bots, "
    "robots, spiders, or scrapers, as well as your use of that data."
    "\n23.2 You agree not to use automated data collection methods to obtain the mobile phone numbers and email addresses of our users, "
    "and you acknowledge that you if you contact our users for the purpose of directing them to your business or website without their express "
    "permission to contact them, then you may be prosecuted under United Arab Emirates laws.";

String callRecord = "24. Call Recording for Real Estate Brokers";
String TOU28 = "Some of the licensed real estate brokers (Brokers) that advertise on our Website subscribe to a service whereby the property "
    "listing has a uniquely identified phone number and the call is automatically recorded for quality and training purposes. By using the Services "
    "you expressly agree to having your phone call recorded when you call a Broker in relation to advertisements in the Property category of the "
    "Website and you agree that no further warning or consent is required.";


String cvSearch = "25. CV Search / Jobs Wanted";
String TOU29 = "25.1 iexchangeit.comis not responsible for the information posted by the job seekers in the Jobs Wanted section or in their CV's."
    "\n25.2 The CV Search is a form of head hunting, it allows recruiters to look through the CV's in our database. However, some of the applicants "
    "may or may not match the job position you are looking to fill."
    "\n25.3 Any fees paid are non-refundable once the package is used."
    "\n25.4 The duration of the CV Search cannot be extended."
    "\n25.5 By placing a job seeking ad in the Jobs Wanted section, the recruiter will have access to the CV uploaded to the job seeker's profile."
    "\n25.6 Once an applicant uploads their CV to their profile, it will be added to our database where recruiters will have access to it for 18 "
    "months.";


String about = "iexchangeit.com is the new innovative classifieds website for users in the Pakistan. Since its launch iexchangeit.com will become "
    "the number one platform for users to buy, sell, exchange or find anything in their community. A community where underused goods are redistributed "
    "to fill a new need, and become wanted again, where non- product assets such as space, skills and money are exchanged and traded in new ways "
    "that don’t always require centralized institutions or ‘middlemen’.";


String privacyPolicy = "We care about your privacy and are committed to protecting your personal data. "
    "This privacy statement will inform you how we handle your personal data, your privacy rights and "
    "how the law protects you. Please read this privacy statement carefully before using our Services."
    "\nIn this privacy statement:\nServices means any products, services, content, features, technologies, "
    "or functions, and all related websites, applications and services offered to you by us.\n\nPlatform "
    "means the websites, mobile apps, mobile sites or other online properties through which we offer our Services."
    "\n\n1. Who are we?\n\nWe at iexchangeit.com are humble technicians bring all sellers and buyers to gather "
    "at one plate form at no cost. and with our services provide great care to both parties.\n2. "
    "What data do we collect about you?\n\n2.1 Data provided through direct interactions\n\nRegistration "
    "and other account information\nWhen you register to use our Services we may collect the following "
    "information about you:\nif you register using your Google account: first name, last name and email "
    "address;\nif you register using your Facebook account: we collect first name and last name as appeared "
    "on your Facebook account and Facebook IDs. In the event you have provided permission to Facebook "
    "through their in-app privacy option (which appears just before you register on our Platform), "
    "we may collect your gender, age or email id depending on the permissions granted by you; and"
    "\nif you register using your mobile number: mobile number.\nDepending on the choices you make during the "
    "log-in to our Services or during the process of engaging our Services, you may opt to give the following "
    "additional personal data:\nyour name;\ne-mail address;\nmobile number; and/or\nyour credit card "
    "details in case you want to purchase our paid services as defined in our Terms of Use.\n\nCommunication "
    "through the chat feature on our Platform\nWhen you use our chat feature to communicate with other users, "
    "we collect information that you choose to provide to other users through this feature."
    "\n2.2 Data we collect automatically when you use of our Services\n\nWhen you interact with our Platform "
    "or use our Services, we automatically collect the following information about you:\nDevice Information"
    "\nWe collect device-specific information such as operating system version and unique identifiers. "
    "For example, the name of the mobile network that you are using. We associate the device identifiers "
    "with your social media account.\nLocation information\nDepending on your device permissions, if you "
    "post an item on our Platform, we automatically collect and process information about your actual location. "
    "We use various technologies to determine location, including IP address, GPS, Wi-Fi access points and mobile "
    "towers. Your location data allows you to see user items near you and helps you in posting items within your "
    "location.\nClient and Log data\nTechnical details, including the Internet Protocol (IP) address of your device, "
    "time zone and operating system. We will also store your login information (registration date, date of last "
    "password change, date of last successful login), type and version of your browser.\nClickstream data\nWe "
    "collect information about your activity on our Platform which includes the sites from which you accessed "
    "our Platform, date and time stamp of each visit, searches you have performed, listings or advertisement "
    "banners you clicked, your interaction with such advertisements or listings, duration of your visit and "
    "the order in which you visit the content on our Platform.\nCookies and Similar Technologies\nWe use "
    "cookies to manage our users’ sessions, to store your preferences language selection and deliver you "
    "relevant advertisements. \"Cookies\" are small text files transferred by a web server to the hard drive "
    "of your device. Cookies may be used to collect the date and time of your visit, your browsing "
    "history, your preferences, and your username. You can set your browser to refuse all or some cookies, "
    "or to alert you when websites set or access cookies. If you disable or refuse cookies, please note that "
    "some parts of our Services/Platform may become inaccessible or not function properly. For more information "
    "on the cookies we use, please see our Policy on Cookies and Similar Technologies, the terms of which are "
    "incorporated into, and form part of, this Privacy Policy by reference.\n2.3 Data from third parties or "
    "publicly available sources.\n\nWe may receive personal data about you from various third parties and "
    "public sources. If you would like more information about this, please contact us using the relevant "
    "contact details set out in section 13.\n\n3. Do we collect data from children?\n\nOur Services are "
    "not intended for children under 16 and we do not knowingly collect data from anyone under 16. If we "
    "become aware that a person under 16 has provided us with personal data, we will delete it immediately.\nIf "
    "you are resident in the Pakistan and under 21, we are not permitted to contract with you directly. "
    "If you are a resident in the Pakistan and under 21 then, by agreeing to this Privacy Policy, "
    "you acknowledge and agree that your guardian has read and consented to its terms on your behalf. "
    "If we seek your consent to process your personal data for a specific purpose in accordance with "
    "this Privacy Policy, consent must be granted on your behalf by your guardian.\n\n4. Why do we process "
    "your personal information?\n\nWe will only use your personal data when the law allows us to. Most "
    "commonly, we will use your personal data in the following circumstances:\nWhere we need to perform "
    "the contract we are about to enter into or have entered into with you.\nWhere it is necessary for "
    "our legitimate interests to improve our Services and to provide you a safe and secure Platform.\nWhere "
    "we need to comply with a legal or regulatory obligation.\nIn certain circumstances, we may also process your "
    "personal data based on your consent. If we do this, we will let you know the purpose and the category of "
    "personal data to be processed at the time we seek your consent.\nWe have set out below a description of the "
    "ways we use your personal data.\n1. For providing access and delivering Services through our Platform\n\nIf you "
    "log in using your mobile number or email id, we use your first name and last name, mobile number and/or "
    "e-mail address to identify you as a user and provide access to our Platform.\nIf you log in using your "
    "Facebook account, we use your first name and last name from your Facebook profile and the Facebook e-mail "
    "address to identify you as a user on our Platform and to provide you access to our Platform.\nThe above "
    ""
    "log-information data is also used by us to deliver our Services to you in accordance with our Terms of Use.\nWe "
    "use your e-mail address and mobile number (by SMS) to make suggestions and recommendations to you about "
    "our Services that may be of interest to you.\nWe process the above information for adequate performance "
    "of our contract with you and on the basis of our legitimate interest in undertaking marketing activities "
    "to offer you Services that may be of your interest.\n2. For improving your experience on the Platform\n\nWe "
    "use clickstream data to:\noffer you tailored content, such as giving you more relevant search results when "
    "using our Services;\nto determine how much time you spend on our Platform and in what manner you navigate "
    "through our Platform in order to understand your interests and to improve our Services based on this data. "
    "For example, we may provide you with suggestions on content that you can visit based on the contents you "
    "have clicked; and\nto monitor and report the effectiveness of the campaign delivery to our business partners "
    "and for internal business analysis.\nWe use your location data for following purposes:\nto compile anonymous "
    "and aggregated information about the characteristics and behaviour of users, including for the purposes of "
    "business analysis, segmentation and development of anonymous profiles;\nto enhance the performance of our "
    "Services and to personalise the content we direct towards you. For example - with the help of location data "
    "we display ad listings which are in your vicinity to improve your buying experience; and\nto measure and "
    "monitor your interaction with the third-party advertisements banners we place on our Platform.\nWith the "
    "help of your log-in information which includes your email id and phone number, we map the different "
    "devices (such as desktop, mobile, tablets) used by you to access our Platform. This allows us to associate "
    "your activity on our Platform across devices and helps us in providing you a seamless experience no matter "
    "which device you use.\nWe process the above information on the basis of our legitimate interest to improve "
    "your experience on our Platform and for adequate performance of our contract with you.\n3. To provide you a "
    "safe and secure Platform\n\nWe use your mobile number, log data and unique device identifiers to administer "
    "and protect our Platform (including troubleshooting, data analysis, testing, fraud prevention, system "
    "maintenance, support, reporting and hosting of data).\nWe analyse your communications done through our "
    "chat feature for fraud prevention and to promote safety by blocking spam or abusive messages that may "
    "have been sent to you by any other user.\nWe process the above information for adequate performance of "
    "our contract with you, to improve our services and on the basis of our legitimate interest to prevent "
    "fraud.\n\n5. How will we inform you about changes in our privacy statement?\n\nWe may amend this privacy "
    "statement from time to time. We will post changes on this page and will let you know by e-mail or through "
    "our Platform. If you or your guardian (as the case may be) do not agree with the changes, you may close "
    "your account by going to account setting and select delete account.\n\n6. Your rights\n\nYou may have "
    "certain legal rights regarding your personal data depending on the country you are in or how we interact "
    "with you. You can learn more about this in this section.\n6.1. Pakistan (\"PAK\") data subjects\n\nIf you"
    "are a data subject in the Pakistan, you will have the following rights:\nRight to request access to your"
    "personal data (commonly known as a “data subject access request”). This enables you to receive a copy of"
    "the personal data we hold about you and to check that we are lawfully processing it.\nRight to request"
    "correction of any of the data we have about you. This enables you to have any incomplete or inaccurate "
    "data we hold about you corrected, though we may need to verify the accuracy of the new data you provide to "
    "us.\nRight to withdraw your consent to the processing of your personal data at any time. This does not "
    "affect the legality of any processing we have already carried out based on the consent given previously."
    "\n6.2. EU General Data Protection Regulation (\"GDPR\") data subjects\n\nIf you are a data subject under "
    "the GDPR, you will have certain additional rights in relation to our handing of your personal information."
    "\nRight to request access to your personal data (commonly known as a \“data subject access request\”). "
    "This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully "
    "processing it.\nRight to request correction of any of the data we have about you. This enables you to "
    "have any incomplete or inaccurate data we hold about you corrected, though we may need to verify the "
    "accuracy of the new data you provide to us.\nRight to withdraw your consent to the processing of your "
    "personal data at any time. This does not affect the legality of any processing we have already carried "
    "out based on the consent given previously.\nRight to request restriction of processing of your personal "
    "data. This enables you to ask us to suspend the processing of your personal data in the following scenarios: "
    "(a) if you want us to establish the data's accuracy; (b) where our use of the data is unlawful; "
    "(c) where you need us to hold the data even if we no longer require it as you need it to establish, "
    "exercise or defend legal claims; or (d) you have objected to our use of your data but we need to verify "
    "whether we have overriding legitimate grounds to use it.\nRight to request erasure of your personal data. "
    "This enables you to ask us to delete or remove personal data where there is no good reason for us continuing "
    "to process it. You also have the right to ask us to delete or remove your personal data where you have "
    "successfully exercised your right to object to processing (see below), where we may have processed your "
    "information unlawfully or where we are required to erase your personal data to comply with local law. "
    "Please note that for certain purposes we may be legally obligated to retain your data. "
    "Please see section 10.\nRight to object to the processing of your personal data where we are relying on a "
    "legitimate interest (or those of a third party) and there is something about your particular situation "
    "which makes you want to object to processing on this ground as you feel it impacts on your fundamental "
    "rights and freedoms. You also have the right to object where we are processing your personal data for "
    "direct marketing purposes. In some cases, we may demonstrate that we have compelling legitimate grounds "
    "to process your information which override your rights and freedoms.\nRight to request for the transfer "
    "of your personal data to you or to a third party. We will provide to you, or a third party you have chosen, "
    "your personal data in a structured, commonly used, machine-readable format. Note that this right only "
    "applies to automated information which you initially provided consent for us to use or where we used the "
    "information to perform a contract with you.\nTo lodge a complaint at any time with your local supervisory "
    "responsible for you as outlined in section 13. However, before you make a complaint to the data protection "
    "authority, we would appreciate the chance to deal with your concerns in the first instance, please reach out "
    "to our Privacy Officer at privacy@iexchangeit.com.\nNo fee usually required: You will not have to pay a fee "
    "to access your personal data (or to exercise any of the other rights). However, we may charge a reasonable "
    "fee if your request is clearly unfounded, repetitive or excessive. Alternatively, we may refuse to comply "
    "with your request in these circumstances.\nTime limit to respond: We try to respond to all legitimate "
    "requests within one month. Occasionally it may take us longer than a month if your request is particularly "
    "complex or you have made several requests. In this case, we will notify you and keep you updated.\n\n7. "
    "Communication and marketing\n\nWe will communicate with you by email, SMS or in app notification in "
    "connection with our Services/Platform to confirm your registration, to inform you in case your ad listing "
    "has become live/expired and for other transactional messages in relation to our Services. As it is imperative "
    "for us to provide you such transactional messages you may not be able to opt-out of such messages.\nHowever, "
    "you can ask us to stop sending you marketing communication at any time by clicking on the opt-out link in "
    "the email or SMS sent to you or by reaching out us on Privacy@iexchangeit.com.\nYou may receive marketing "
    "communications from us if you:\nhave requested such information from us;\nuse our Platform or Services;\nprovided "
    "us with your details when you entered a competition; or\nregistered for a promotion.\n\n8. Who do we share "
    "your data with?\n\nWe may have to share your personal data with the parties set out below for the purposes "
    "set out in section 4 above.\nThird Party Service Providers: We use third party service providers to help us "
    "deliver certain aspect of our Services for example, cloud storage facilities such as Amazon Web Services and "
    "Microsoft Azure. Service providers may be located inside or outside of the EEA and Pakistan.\nWe conduct "
    "checks on our third-party service providers and require them to respect the security of your personal data "
    "and to treat it in accordance with the law. We do not allow them to use your personal data for their own "
    "purposes and only permit them to process your personal data for specified purposes and in accordance with "
    "our instructions.\nAdvertising and analytics providers: In order to improve our Services, we will sometimes "
    "share your non-identifiable information with analytics providers that help us analyse how people are using "
    "our Platform/Service. We share your information with them in non identifiable form for monitoring and reporting "
    "the effectiveness of the campaign delivery to our business partners and for internal business analysis. For "
    "further details about our advertisers and analytics provider please refer to our Policy for Cookies and "
    "similar Technologies.\nLaw enforcement authorities, regulators and others: We may disclose your personal "
    "data to law enforcement authorities, regulators, governmental or public bodies and other relevant third "
    "parties to comply with any legal or regulatory requirements.\nWe may choose to sell, transfer, or merge parts of "
    "our business or our assets. Alternatively, we may seek to acquire other businesses or merge with them. If a "
    "change happens to our business, then the new owners may use your personal data in the same way as set out in "
    "this privacy statement.\nPublicly available information: When you post an item for sale using our Services, "
    "you may choose to make certain personal information visible to other users. This may include your first name, "
    "last name, your email address, your location and your contact number. Please note, any information you provide "
    "to other users can always be shared by them with others so please exercise discretion in this respect.\n\n9. "
    "International transfers\n\nYou agree that we may transfer your personal data to third parties inside and "
    "outside of the Pakistan.\nTo the extent that the GDPR applies to our relationship with you, then whenever "
    "we transfer your personal data out of the EEA or Pakistan, we ensure a similar degree of protection is "
    "afforded to it by ensuring at least one of the following safeguards is implemented:\nWe may transfer "
    "your personal data to countries that have been deemed to provide an adequate level of protection for "
    "personal data by the European Commission. For further details, see European Commission: Adequacy of the "
    "protection of personal data in non-EU countries.\nWhere we transfer your personal data to countries that "
    "have not been deemed to provide an adequate level of protection for personal data by the European "
    "Commission we will ensure that adequate safeguards are put in place, such as specific contract clauses "
    "that have been approved by the European Commission for use with third parties, which give personal data "
    "the same protection it has in the European Union. For further details, see European Commission: Model "
    "contracts for the transfer of personal data to third countries.\nWhere appropriate we may need to rely "
    "upon other derogations under the GDPR that allow for transfers out of the EEA to countries that are not "
    "deemed to provide adequate levels of protection or were we do not have adequate safeguards. For further "
    "details please see European Commission : Working Party 29 Guidelines on Article 49 GDPR Derogations.\nWhere w"
    "e use service providers based in the US, we may transfer data to them if they are part of the Privacy Shield "
    "which requires them to provide similar protection to personal data shared between the Europe and the US. For "
    "further details, see European Commission: EU-US Privacy Shield.\nYou can receive the copy of relevant and "
    "implemented safeguards by contacting us at privacy@iexchangeit.com.\n\n10. Where do we store your data and "
    "for how long?\n\nThe data we collect about you may be stored and processed inside as well as outside the "
    "EEA and Pakistanin secure servers in order to provide the best possible user experience. For example – for "
    "fast website or mobile application build up.\nWe will only retain your personal data for as long as necessary "
    "to fulfil the purposes we collected it for, including for the purposes of satisfying any legal, accounting, "
    "or reporting requirements.\nTo determine the appropriate retention period for personal data, we consider the "
    "amount, nature, and sensitivity of the personal data, the potential risk of harm from unauthorised use or "
    "disclosure of your personal data, the purposes for which we process your personal data and whether we can "
    "achieve those purposes through other means, and the applicable legal requirements.\nIn case you have any "
    "queries in relation to retention period of your data please contact us at privacy@iexchangeit.com.\n\n11. "
    "Technical and organisational measures and processing security\n\nAll the information we receive about "
    "you are stored on secure servers and we have implemented technical and organisational measures that are "
    "suitable and necessary to protect your personal data. OLX continually evaluates the security of its network "
    "and adequacy of its internal information security program which is designed to (a) help secure your "
    "data against accidental or unlawful loss, access or disclosure, (b) identify reasonably foreseeable "
    "risks to the security of the OLX network, and (c) minimize security risks, including through risk "
    "assessment and regular testing. In addition, we ensure that all payment data are encrypted using SSL "
    "technology.\nPlease note, despite the measures we have implemented to protect your data, the transfer of "
    "data through the Internet or other open networks is never completely secure and there is a risk that your "
    "personal data may be accessed by unauthorised third parties.\n\n12. Links to third-party websites\n\nOur "
    "Platform may contain links to third party websites or apps. If you click on one of these links, please note "
    "that each one will have its own privacy policy. We do not control these websites/apps and are not responsible "
    "for those policies. When you leave our Platform, we encourage you to read the privacy notice of every website "
    "you visit.\n\n13. Contact\n\nFor any additional information or to exercise your rights, please contact our"
    " Privacy Officer at privacy@iexchangeit.com, or go to the Help Section in our Platform.\n14. Changes to "
    "this Policy\n\nWe may amend this Privacy Policy from time to time to keep it up to date with legal "
    "requirements and the way we operate our business. Please regularly check this page for the latest "
    "version of this Privacy Policy. If we make material changes to this Privacy Policy, we will seek to inform "
    "you by notice on our website or application, or email (\"Notice of Change\").\nYour continued use of our "
    "Services following an amendment or Notice of Change indicates your or your guardian's acceptance "
    "(as the case may be) of any changes.";



